### ISSUE TITLE
Build fails, Stdio package.

### ISSUE THREAD

**Issue by jpfeltracco** [LWJGL/lwjgl3-demos#11]
When I clone the repo and run `mvn clean install` the build fails with the following error. Removing the lines referencing the Stdio class allows the build to continue.

> [INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building lwjgl3-demos 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ lwjgl3-demos ---
[INFO] Deleting /home/jpfeltracco/repos/lwjgl3-demos/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ lwjgl3-demos ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 155 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ lwjgl3-demos ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 70 source files to /home/jpfeltracco/repos/lwjgl3-demos/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/jpfeltracco/repos/lwjgl3-demos/src/org/lwjgl/demo/bgfx/Demo.java:[11,29] cannot find symbol
  symbol:   class Stdio
  location: package org.lwjgl.system.libc
[ERROR] /home/jpfeltracco/repos/lwjgl3-demos/src/org/lwjgl/demo/bgfx/Demo.java:[274,62] cannot find symbol
  symbol:   variable Stdio
  location: class org.lwjgl.demo.bgfx.Demo
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.919 s
[INFO] Finished at: 2016-11-30T15:39:01-05:00
[INFO] Final Memory: 17M/273M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project lwjgl3-demos: Compilation failure: Compilation failure:
[ERROR] /home/jpfeltracco/repos/lwjgl3-demos/src/org/lwjgl/demo/bgfx/Demo.java:[11,29] cannot find symbol
[ERROR] symbol:   class Stdio
[ERROR] location: package org.lwjgl.system.libc
[ERROR] /home/jpfeltracco/repos/lwjgl3-demos/src/org/lwjgl/demo/bgfx/Demo.java:[274,62] cannot find symbol
[ERROR] symbol:   variable Stdio
[ERROR] location: class org.lwjgl.demo.bgfx.Demo
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by Spasi** [comment]
Thanks!
