### ISSUE TITLE
SWT async recursion is bad for Eclipse RCP environment

### ISSUE THREAD

**Issue by dveyarangi** [LWJGL/lwjgl3-demos#13]
Regarding the example at https://github.com/LWJGL/lwjgl3-demos/blob/master/src/org/lwjgl/demo/opengl/swt/SwtDemo.java

The proposed recursive call for 
display.asyncExec(new Runnable() {
        renderThings();
        display.asyncExec( this )
}
means that the async job queue is never empty. When running in Eclipse RCP environment, repositioning parts of RCP application waits until the queue is finished, but since this never happens, an attempt to move parts causes the entire application to stuck forever.

**Comment by httpdigest** [comment]
Thanks for the info with RCP!
Would the following be okay in RCP? (does work in non-RCP)
```Java
display.asyncExec(new Runnable() {
  display.timerExec(0, new Runnable() {
    renderThings();
  });
});
```
