### ISSUE TITLE
Memory operations using empty part of the buffer

### ISSUE THREAD

**Issue by localgoat** [LWJGL/lwjgl3-demos#20]
I'm not sure if I'm being an idiot here, I was looking at org/lwjgl/demo/vulkan/TwoRotatingTrianglesInvDepthDemo.java, and it seems to me that it's using the size of the unused piece of the buffer as the amount of data stored.

This is line 915 (just one example of the instances that seem wrong to me):
`memCopy(memAddress(vertexBuffer), data, vertexBuffer.remaining());`

Should it not be:
`memCopy(memAddress(vertexBuffer), data, vertexBuffer.position());`
?

Sorry if I'm wrong.

**Comment by httpdigest** [comment]
Actually no. The hint as to why not can be found in these two lines: https://github.com/LWJGL/lwjgl3-demos/blob/master/src/org/lwjgl/demo/vulkan/TwoRotatingTrianglesInvDepthDemo.java#L853-L854

fb is the FloatBuffer being filled (which aliases the ByteBuffer `vertexBuffer`). So, the position of `vertexBuffer` never changes and `vertexBuffer.capacity()` could have been used as well.

**Comment by localgoat** [comment]
Thanks for the reply.
