### ISSUE TITLE
SpaceGame demo Camera angular acceleration is way too high

### ISSUE THREAD

**Issue by TheMrMilchmann** [LWJGL/lwjgl3-demos#22]
Currently, rotating the camera via the exposed controls results in the camera spinning very fast before slowing down. The issue is visible when pressing either the `Q` or `E` button, or by dragging the mouse with the right mouse button pressed.

I'm quite sure that is not intended. However, I could not find the change that "broke" it upon taking a quick glance at the files history.

(A video showcasing the current behavior can be found here: https://youtu.be/fhPqu4c41u0).

**Comment by httpdigest** [comment]
Thanks for reporting this bug! I finally could nail it down to a change in JOML introduced with this refactoring: https://github.com/JOML-CI/JOML/commit/2c0a1aa5c912c0551566020a7846f271497d598d
Fixed with: https://github.com/JOML-CI/JOML/commit/bfffd19db1d8c6efe9775e5aab8b85e1f76c66fa
