### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by jonlareau** [LWJGL/lwjgl3-demos#26]
Cloned the repo, ran "mvnw package" as indicated in readme, following error produced.  Seems to be having issues finding the opengl, par, bgfx and vma natives listed in the pom.xml.

[INFO] Scanning for projects...
[INFO]
[INFO] -----------------------< org.lwjgl:lwjgl3-demos >-----------------------
[INFO] Building lwjgl3-demos 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.785 s
[INFO] Finished at: 2019-10-03T12:02:50-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project lwjgl3-demos: Could not resolve dependencies for project org.lwjgl:lwjgl3-demos:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.lwjgl:lwjgl-opengl:jar:natives-windows:3.2.4-SNAPSHOT, org.lwjgl:lwjgl-par:jar:natives-windows:3.2.4-SNAPSHOT, org.lwjgl:lwjgl-bgfx:jar:natives-windows:3.2.4-SNAPSHOT, org.lwjgl:lwjgl-vma:jar:natives-windows:3.2.4-SNAPSHOT, org.lwjgl:lwjgl-shaderc:jar:natives-windows:3.2.4-SNAPSHOT: Failure to find org.lwjgl:lwjgl-opengl:jar:natives-windows:3.2.4-20190903.201424-1 in https://oss.sonatype.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of oss.sonatype.org has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by jonlareau** [comment]
git branch -v
* master c8c5608 Create TLAS with multiple instances

**Comment by jonlareau** [comment]
Note: Adjusting "${lwjgl.version}" to explicitly read "3.2.3-SNAPSHOT" ONLY for lwjgl-shaderc, bgfx, vma, par, and opengl natives allows everything to build.

**Comment by httpdigest** [comment]
Cannot reproduce. Cleared my local ~/.m2/repository repo cache and ran `./mvnw clean package` again without any errors. Maybe this was a slight hickup on oss.sonatype.org's side and is now fixed. Try again with forcing updated of snapshot versions via `./mvnw clean package -U`.

**Comment by jonlareau** [comment]
Same here.  Successfully built after clearing. Thanks.  Very odd.  But working now.
