### ISSUE TITLE
Texture Demo for the vulkan demos?

### ISSUE THREAD

**Issue by codedcosmos** [LWJGL/lwjgl3-demos#28]
The vulkan demo collection is pretty thorough with the basic ClearScreenDemo, 3D with depth (TwoRotatingTrianglesInvDepthDemo) and ray tracing.

I'm quite new to vulkan, and would like it if a textured quad demo could be added to the vulkan demos. I might end up writing it myself once I figure out this api in depth.

**Comment by httpdigest** [comment]
If you are interested in a very thorough set of demos, then do have a look at Sascha Willems' repo https://github.com/SaschaWillems/Vulkan/tree/master/examples
This lwjgl3-demos repo here should then serve as a way to see how to translate the C language features to Java.

**Comment by codedcosmos** [comment]
I'm going to close this as, I don't think anyone needs to take action on behalf of lwjgl.
