### ISSUE TITLE
Vulkan ClearScreenDemo requires discrete gpu

### ISSUE THREAD

**Issue by 8Keep** [LWJGL/lwjgl3-demos#29]
I can run all Vulkan demos except the NvRayTracing (expected, right?) and ClearScreenDemo. I am on a mobile Intel GPU. I can modify the demo lines 232-233 and get rid of the part requiring `VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU`, and the demo then works fine. The two NvRayTracing demos also have lines requiring `VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU`, and none of the other demos have that.

**Comment by httpdigest** [comment]
Thanks! Fixed.
