### ISSUE TITLE
There is no OpenAl demos ??

### ISSUE THREAD

**Issue by diego3** [LWJGL/lwjgl3-demos#3]
I saw this link https://github.com/LWJGL/lwjgl3/tree/master/src/tests/org/lwjgl/demo/openal

on forum http://forum.lwjgl.org/index.php?topic=5658.0

but if you click on it, we are redirected to a 404 page not found at github domain!

**Comment by httpdigest** [comment]
LWJGL3's directory structure has changed since then.
See: https://github.com/LWJGL/lwjgl3/tree/master/modules/core/src/test/java/org/lwjgl/demo/openal
