### ISSUE TITLE
does not start on Linux

### ISSUE THREAD

**Issue by KVAC** [LWJGL/lwjgl3-demos#31]
git commit: 1844a596ec9770e36af820e4ca7b7ee2e6705f40
--------------------------------------------
java:
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
--------------------------------------------
msgs from systemd logs in file.
--------------------------------------------
msgs from console:
############################
Press W/S to move forward/backward
Press L.Ctrl/Spacebar to move down/up
Press A/D to strafe left/right
Press Q/E to roll left/right
Hold the left mouse button to shoot
Hold the right mouse button to rotate towards the mouse cursor
[LWJGL] OpenGL debug message
        ID: 0x8
        Source: SHADER COMPILER
        Type: OTHER
        Severity: NOTIFICATION
        Message: FS SIMD8 shader: 10 inst, 0 loops, 820 cycles, 0:0 spills:fills, 2 sends, scheduled with mode top-down, Promoted 0 constants, compacted 160 to 144 bytes.
[LWJGL] OpenGL debug message
        ID: 0x9
        Source: SHADER COMPILER
        Type: OTHER
        Severity: NOTIFICATION
        Message: FS SIMD16 shader: 13 inst, 0 loops, 836 cycles, 0:0 spills:fills, 2 sends, scheduled with mode top-down, Promoted 0 constants, compacted 208 to 192 bytes.
FATAL ERROR in native method: Thread[main,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
        at org.lwjgl.opengl.GL11.glEnableClientState(Native Method)
        at org.lwjgl.demo.game.SpaceGame.init(SpaceGame.java:330)
        at org.lwjgl.demo.game.SpaceGame.run(SpaceGame.java:1037)
        at org.lwjgl.demo.game.SpaceGame.main(SpaceGame.java:1057)
############################

[LOGGGGG.txt](https://github.com/LWJGL/lwjgl3-demos/files/5540236/LOGGGGG.txt)

**Comment by httpdigest** [comment]
This is not an issue with the demo itself but with either the OpenGL driver not being OpenGL 2.0 compliant or maybe the wrong context version is requested by GLFW or OpenGL function pointers could not be obtained by LWJGL.

**Comment by KVAC** [comment]
glxinfo | grep OpenGL

OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2)
OpenGL core profile version string: 4.2 (Core Profile) Mesa 20.2.2
OpenGL core profile shading language version string: 4.20
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 20.2.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 20.2.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00

**Comment by httpdigest** [comment]
Well, first output `GL_VERSION` and simply play around with GLFW window hints, for example `GLFW_CONTEXT_VERSION_MAJOR` / `GLFW_CONTEXT_VERSION_MINOR`, to convince that Mesa driver to give you an OpenGL <= 2.1 context instead of an OpenGL >= 3.0 core profile context.
Normally, one does this by not specifying any context version or profile window hints with e.g. drivers from Nvidia and AMD. I have no idea how things work with Mesa.

**Comment by KVAC** [comment]
GL_VERSION_1_1:                                                OK 
GL_VERSION_1_2:                                                OK 
GL_VERSION_1_2_1:                                              OK 
GL_VERSION_1_3:                                                OK 
GL_VERSION_1_4:                                                OK 
GL_VERSION_1_5:                                                OK 
GL_VERSION_2_0:                                                OK 
GL_VERSION_2_1:                                                OK 
GL_VERSION_3_0:                                                OK 
GL_VERSION_3_1:                                                MISSING 
GL_VERSION_3_2:                                                MISSING 
GL_VERSION_3_3:                                                MISSING 
GL_VERSION_4_0:                                                MISSING 
GL_VERSION_4_1:                                                MISSING 
GL_VERSION_4_2:                                                MISSING 
GL_VERSION_4_3:                                                MISSING 
GL_VERSION_4_4:                                                MISSING 
GL_VERSION_4_5:                                                MISSING 
GL_VERSION_4_6:                                                MISSING

**Comment by httpdigest** [comment]
No, I meant that you should query `GL_VERSION` (via `glGetString` that is)

**Comment by KVAC** [comment]
GLFW.GLFW_CONTEXT_VERSION_MAJOR null
GLFW.GLFW_CONTEXT_VERSION_MINOR null

**Comment by KVAC** [comment]
I was able to run this. I added ALL dependencies from https://www.lwjgl.org/customize 'changed source and resource paths and it worked.
close the topic
