### ISSUE TITLE
tag the demos repo to match with the main LWJGL3 release

### ISSUE THREAD

**Issue by chirontt** [LWJGL/lwjgl3-demos#33]
Can we have some tags matching the demos to be compatible with the LWJGL3 release?

Keeping the demos working with the latest and greatest features of LWJGL3 *snapshot* is great, but sometimes we need to run them against the official (current) release from Maven Central just to see what the demos are all about.

Currently I need to run the demos against the 3.2.3 version from Maven Central, and I'm having big trouble just to compile them. If we have some tag marking them compatible with the 3.2.3 release, it would be a great help.

**Comment by httpdigest** [comment]
That's a good proposal, but it's difficult to achieve looking at the numerous LWJGL 3 versions already being around.
The demos will continue to be developed/maintained against the latest _snapshot build_ of the latest LWJGL version and I will probably not test them against LWJGL _release_ versions.
