### ISSUE TITLE
whats the intended read order of the tutorials after intro1-5?

### ISSUE THREAD

**Issue by nathanbowley98** [LWJGL/lwjgl3-demos#45]
I finished intro1-5 but now don't know which one im supposed to look at next, is there a order im supposed to read through?

**Comment by httpdigest** [comment]
There is no particular order. The introduction applications under https://github.com/LWJGL/lwjgl3-demos/tree/main/src/org/lwjgl/demo/intro are merely meant to give you an idea about how the native API constructs map to LWJGL. Continuing from there, it's probably best to seek some specialized (and not LWJGL-related) tutorials about the native API that you want to learn more about, like OpenGL or Vulkan. Then, you should hopefully be able to transfer the things leant there (probably via C or C++) to LWJGL/Java.
